server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      enabled: true

    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/task/user/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/task/order/**
         
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/task/payment/**		

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG